export interface CompanyReview {
  id: string
  role: string
  employment_status: 'Current' | 'Former'
  rating: number
  date: string
  pros: string
  cons: string
  anonymous: boolean
  author_name?: string
  helpful_count: number
  salary?: string
}

export interface Company {
  id: string
  name: string
  industry: string
  size: string
  location: string
  description: string
  overall_rating: number
  ratings: {
    work_life_balance: number
    culture: number
    management: number
    career_growth: number
    compensation: number
  }
  benefits: string[]
  reviews: CompanyReview[]
}

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'the-harbour-table',
    name: 'The Harbour Table',
    industry: 'Restaurant',
    size: '11–50 employees',
    location: 'Cape Town, V&A Waterfront',
    description:
      'The Harbour Table is a busy upscale waterfront restaurant at the V&A Waterfront serving modern South African cuisine with a focus on fresh seafood. Known for its views of the harbour and a high-energy front-of-house team, we serve a mix of tourists and Cape Town locals. We pride ourselves on genuine hospitality and a no-nonsense management style.',
    overall_rating: 3.8,
    ratings: {
      work_life_balance: 3.5,
      culture: 4.0,
      management: 3.6,
      career_growth: 3.2,
      compensation: 3.8,
    },
    benefits: ['Staff meals on shift', 'Tips shared equally', 'Flexible rosters', 'Public holiday premium pay', 'Staff discount'],
    reviews: [
      {
        id: 'ht-r1',
        role: 'Waiter',
        employment_status: 'Current',
        rating: 4,
        date: '2025-11',
        pros: 'The tips are genuinely good, especially in summer when the tourists come through. Team is mostly friendly and management is fair — they don\'t shout at you. Strong regulars who tip well on weekends.',
        cons: 'Very busy during school holidays and December — you can do 12-hour shifts back to back with very little break time. Parking near the Waterfront is a pain if you don\'t have a car allowance.',
        anonymous: true,
        helpful_count: 14,
        salary: 'R6 500/month + tips (averaging R2 000–R4 000 extra in season)',
      },
      {
        id: 'ht-r2',
        role: 'Junior Sous Chef',
        employment_status: 'Former',
        rating: 3,
        date: '2025-08',
        pros: 'Good experience for a younger chef — busy kitchen, you learn fast. The Head Chef is technically strong and teaches if you ask. Fresh product quality is excellent.',
        cons: 'Kitchen culture can be intense. Overtime is expected but not always compensated properly. Difficult to take annual leave in peak season. Left for a role with better work-life balance.',
        anonymous: false,
        author_name: 'Sipho M.',
        helpful_count: 9,
        salary: 'R14 000/month',
      },
      {
        id: 'ht-r3',
        role: 'Floor Manager',
        employment_status: 'Former',
        rating: 4,
        date: '2025-03',
        pros: 'Great exposure managing a large floor team. Excellent location — really no better setting in Cape Town. Learning to manage a diverse team in high pressure situations is a career booster.',
        cons: 'Communication between kitchen and FOH could be better. Rosters sometimes only come out Wednesday for the weekend which makes personal planning hard.',
        anonymous: true,
        helpful_count: 6,
      },
    ],
  },
  {
    id: 'radisson-blu-gauteng',
    name: 'The Radisson Blu Gauteng',
    industry: 'Hotel',
    size: '201–500 employees',
    location: 'Sandton, Johannesburg',
    description:
      'The Radisson Blu Gauteng is a five-star business hotel in the heart of Sandton, catering predominantly to corporate guests and international travellers. The hotel operates multiple food and beverage outlets including a fine dining restaurant, rooftop bar, and all-day dining venue. As part of a global hotel group, employees benefit from structured HR processes and international career pathways.',
    overall_rating: 3.9,
    ratings: {
      work_life_balance: 3.4,
      culture: 4.1,
      management: 3.8,
      career_growth: 4.3,
      compensation: 3.6,
    },
    benefits: ['Medical aid contribution', 'Staff meals', 'Provident fund', 'Global hotel network discounts', 'Training bursaries', 'Employee wellness programme'],
    reviews: [
      {
        id: 'rad-r1',
        role: 'Front Desk Receptionist',
        employment_status: 'Current',
        rating: 4,
        date: '2025-12',
        pros: 'Working in a 5-star environment is great for your CV and your personal development. The training is structured and professional — I feel like I\'m genuinely learning. Medical aid contribution is a big deal at this salary level.',
        cons: 'Shift work is relentless — public holidays, Christmas, New Year. The corporate environment can feel impersonal. Pay increases are very small year on year despite the workload.',
        anonymous: true,
        helpful_count: 21,
        salary: 'R9 200/month',
      },
      {
        id: 'rad-r2',
        role: 'Sous Chef',
        employment_status: 'Current',
        rating: 4,
        date: '2025-10',
        pros: 'International standards mean you are cooking at a high level. The purchasing power of a big group means quality ingredients. Opportunity to transfer to other Radisson properties globally — real career pathway.',
        cons: 'Kitchen politics exist at every level. Night shifts for the rooftop bar can be rough when you\'re also expected for morning prep the next day. Canteen food for staff meals isn\'t great.',
        anonymous: false,
        author_name: 'Lebo K.',
        helpful_count: 17,
        salary: 'R21 000/month',
      },
      {
        id: 'rad-r3',
        role: 'Housekeeping Attendant',
        employment_status: 'Former',
        rating: 3,
        date: '2025-06',
        pros: 'Stable employment with a big company. UIF, provident fund all properly administered — which is not always the case in hospitality. Colleagues are supportive.',
        cons: 'The physical demand is high — 14–16 rooms a day is too many. Management in housekeeping is under constant pressure from front desk and that stress rolls downhill. Very little recognition for hard work.',
        anonymous: true,
        helpful_count: 11,
        salary: 'R7 500/month',
      },
    ],
  },
  {
    id: 'breezy-rooftop-bar',
    name: 'Breezy Rooftop Bar',
    industry: 'Bar / Nightlife',
    size: '11–50 employees',
    location: 'Umhlanga, Durban',
    description:
      'Breezy Rooftop Bar is one of Umhlanga\'s most popular cocktail bars, perched above the beachfront strip with panoramic views of the Indian Ocean. With a strong focus on craft cocktails, DJ nights, and a lively after-work crowd, Breezy is known for its energetic atmosphere. The team is young and fast-paced, and the bar draws a loyal local following alongside visiting holidaymakers.',
    overall_rating: 3.6,
    ratings: {
      work_life_balance: 2.8,
      culture: 4.2,
      management: 3.4,
      career_growth: 3.0,
      compensation: 3.8,
    },
    benefits: ['Tips shared equally among bar team', 'Shift drinks after closing', 'Flexible scheduling', 'Staff events', 'Cocktail training programme'],
    reviews: [
      {
        id: 'breezy-r1',
        role: 'Bartender',
        employment_status: 'Current',
        rating: 4,
        date: '2025-11',
        pros: 'Best cocktail training I\'ve had anywhere in Durban. The owner actually invests in the team — we did a full spirits and cocktail course. Tips on Friday/Saturday nights can double your monthly pay. The vibe is electric when it\'s busy.',
        cons: 'The hours are rough — 10pm to 3am on weekends destroys your social life outside of work. Closing duties add another hour minimum. Getting Uber home at 4am from Umhlanga is expensive.',
        anonymous: true,
        helpful_count: 19,
        salary: 'R7 500/month + tips averaging R3 000–R5 000/month',
      },
      {
        id: 'breezy-r2',
        role: 'Bar Supervisor',
        employment_status: 'Former',
        rating: 3,
        date: '2025-07',
        pros: 'Good experience running bar operations. Learned a lot about inventory control and stock management. Location and the brand are great for your CV.',
        cons: 'Management makes promises about salary reviews that never materialise. Very little structure — procedures change week to week depending on who\'s in a good mood. Left after 14 months for a venue with better management.',
        anonymous: true,
        helpful_count: 8,
      },
      {
        id: 'breezy-r3',
        role: 'Waitress',
        employment_status: 'Former',
        rating: 4,
        date: '2025-09',
        pros: 'Fun environment, great colleagues, the tips from the bar area are generous. Summer in Umhlanga is genuinely exciting when the place is packed.',
        cons: 'Understaffed on busy nights — I was regularly running tables I couldn\'t cope with alone. Would be a 5-star job with proper staffing levels.',
        anonymous: false,
        author_name: 'Ntombi D.',
        helpful_count: 13,
        salary: 'R6 000/month + tips',
      },
    ],
  },
  {
    id: 'rustenberg-estate',
    name: 'Rustenberg Estate',
    industry: 'Wine Estate / Guesthouse',
    size: '11–50 employees',
    location: 'Stellenbosch, Western Cape',
    description:
      'Rustenberg Estate is a historic wine farm and five-star guesthouse in the heart of the Stellenbosch Winelands. Offering award-winning wines, a fine dining restaurant, and exclusive accommodation, Rustenberg attracts high-end local and international guests. The estate operates with a small, close-knit team where standards are high and attention to detail is non-negotiable.',
    overall_rating: 4.1,
    ratings: {
      work_life_balance: 3.9,
      culture: 4.4,
      management: 4.0,
      career_growth: 3.3,
      compensation: 3.7,
    },
    benefits: ['Accommodation available', 'Estate wines on shift', 'Staff meals', 'Annual bonus', 'Wine knowledge training'],
    reviews: [
      {
        id: 'rust-r1',
        role: 'Housekeeping Supervisor',
        employment_status: 'Current',
        rating: 4,
        date: '2025-10',
        pros: 'Beautiful place to work — waking up on a wine estate every morning never gets old. Management genuinely cares about the property and by extension the team. The guests are respectful, which makes a huge difference.',
        cons: 'Small team means when someone is sick, the rest of us cover. Can be isolating if you\'re used to a city environment — Stellenbosch is quiet midweek. Career growth opportunities are limited given the small size.',
        anonymous: true,
        helpful_count: 12,
        salary: 'R9 500/month',
      },
      {
        id: 'rust-r2',
        role: 'Wine Steward / Sommelier',
        employment_status: 'Current',
        rating: 5,
        date: '2025-12',
        pros: 'Dream job for a wine person — you\'re literally surrounded by it. The estate invests in WSET training. Guests are knowledgeable wine enthusiasts which makes the job genuinely interesting. Tips from wine tastings are very good.',
        cons: 'Seasonal ups and downs — December and harvest season are intense, July is very quiet. Salary base is modest; the extras make it work.',
        anonymous: false,
        author_name: 'Charl V.',
        helpful_count: 22,
        salary: 'R11 000/month + tips',
      },
      {
        id: 'rust-r3',
        role: 'Kitchen Porter',
        employment_status: 'Former',
        rating: 3,
        date: '2025-05',
        pros: 'Stable job on a beautiful property. Meals on shift are excellent — you eat what the restaurant kitchen preps. Transport subsidy provided.',
        cons: 'Hard physical work for the pay. Progression from kitchen porter to anything else in the kitchen requires pushing management consistently. Left for a better opportunity in Cape Town.',
        anonymous: true,
        helpful_count: 5,
        salary: 'R5 200/month',
      },
    ],
  },
  {
    id: 'origin-coffee-roasting',
    name: 'Origin Coffee Roasting',
    industry: 'Coffee Shop / Roastery',
    size: '51–100 employees',
    location: 'Cape Town, De Waterkant',
    description:
      'Origin Coffee Roasting is one of South Africa\'s most respected specialty coffee brands, with their flagship café and roastery in De Waterkant and multiple locations across Cape Town. They roast single-origin beans in-house and are known for their meticulous approach to coffee quality, barista training, and coffee education. Working at Origin means being part of a team that takes coffee seriously at every level.',
    overall_rating: 4.3,
    ratings: {
      work_life_balance: 3.8,
      culture: 4.7,
      management: 4.2,
      career_growth: 4.0,
      compensation: 3.6,
    },
    benefits: ['Free coffee on shift', 'Specialty coffee education', 'Competition team participation', 'Staff beans at cost', 'Flexible hours for studies'],
    reviews: [
      {
        id: 'orig-r1',
        role: 'Barista',
        employment_status: 'Current',
        rating: 5,
        date: '2025-11',
        pros: 'If coffee is your passion, this is the best employer in Cape Town. The training is world-class — I\'ve learned more here in 8 months than in 3 years elsewhere. Management respects your craft. Good team culture, no drama.',
        cons: 'Pay is on the lower end for the skill level required. If you\'re purely motivated by money, look elsewhere. Peak hours in the morning are very intense — queue management is an art.',
        anonymous: true,
        helpful_count: 29,
        salary: 'R6 000/month',
      },
      {
        id: 'orig-r2',
        role: 'Senior Barista',
        employment_status: 'Current',
        rating: 4,
        date: '2025-09',
        pros: 'Origin sends their top baristas to coffee competitions and the exposure is incredible. Coffee sourcing trips to Ethiopia and Rwanda are available for senior staff. The brand opens doors in the industry.',
        cons: 'Advancement to management level requires patience — positions don\'t open up often. Some of the roastery admin processes are disorganised. Morning shift starts at 6:30am which is brutal in winter.',
        anonymous: false,
        author_name: 'Thandeka N.',
        helpful_count: 18,
        salary: 'R7 800/month',
      },
      {
        id: 'orig-r3',
        role: 'Café Assistant',
        employment_status: 'Former',
        rating: 4,
        date: '2025-04',
        pros: 'Great introduction to specialty coffee. Friendly team, no toxic hierarchy. The De Waterkant café is beautiful and the customers are mostly pleasant.',
        cons: 'Entry level pay is tough in Cape Town with the cost of living. Part-time hours weren\'t always consistent. Left to pursue full-time studies.',
        anonymous: true,
        helpful_count: 7,
        salary: 'R5 500/month (part-time)',
      },
    ],
  },
  {
    id: 'premier-event-catering',
    name: 'Premier Event Catering',
    industry: 'Event Catering',
    size: '51–200 employees',
    location: 'Johannesburg',
    description:
      'Premier Event Catering is a Johannesburg-based catering company specialising in corporate events, year-end functions, product launches, and private celebrations. Operating across multiple venues in and around Joburg and Pretoria, Premier staffs events with experienced waiters, chefs, and event coordinators. The company is known in the industry for reliable, large-scale event execution.',
    overall_rating: 3.2,
    ratings: {
      work_life_balance: 2.9,
      culture: 3.4,
      management: 3.0,
      career_growth: 2.8,
      compensation: 3.5,
    },
    benefits: ['Transport provided to events', 'Meals on event days', 'Flexible pick-and-choose shifts', 'Holiday peak bonuses'],
    reviews: [
      {
        id: 'prem-r1',
        role: 'Event Waiter',
        employment_status: 'Current',
        rating: 3,
        date: '2025-12',
        pros: 'Great for extra income alongside another job. You choose which events to accept — no obligation to take every shift. Payment is reliably on time which is important for casual work. Good way to network across Joburg\'s corporate venues.',
        cons: 'No job security — if events dry up in Q1, there\'s no income. Management communication is poor; sometimes briefings happen 15 minutes before guests arrive. The transport provided is not always comfortable.',
        anonymous: true,
        helpful_count: 16,
        salary: 'R200–R350/shift',
      },
      {
        id: 'prem-r2',
        role: 'Event Supervisor',
        employment_status: 'Former',
        rating: 3,
        date: '2025-08',
        pros: 'Good networking — you work with some of Joburg\'s biggest brands. Events management experience looks excellent on your CV. You learn to think on your feet.',
        cons: 'Permanent staff are treated very differently from casual staff even when they do the same work. Training for new staff at big events is inadequate — they\'re thrown in the deep end.',
        anonymous: false,
        author_name: 'Kagiso M.',
        helpful_count: 11,
      },
      {
        id: 'prem-r3',
        role: 'Casual Waiter',
        employment_status: 'Former',
        rating: 3,
        date: '2025-10',
        pros: 'Flexible and decent pay per shift. Work in cool venues — some events at places you\'d never otherwise get into.',
        cons: 'They overbook staff for big events so not everyone always gets a full shift. You sometimes travel far for a 4-hour event.',
        anonymous: true,
        helpful_count: 4,
        salary: 'R200/shift + transport',
      },
    ],
  },
  {
    id: 'pepperclub-hotel',
    name: 'The Pepperclub Hotel',
    industry: 'Hotel',
    size: '51–200 employees',
    location: 'Cape Town, Green Point',
    description:
      'The Pepperclub Hotel is a four-star boutique hotel in Green Point, Cape Town, close to the Cape Town Stadium and within easy reach of the City Bowl. Popular with business travellers and sports tourists, Pepperclub offers a full-service hospitality experience including a restaurant, bar, rooftop pool, and conference facilities. The hotel has a reputation for a warm, personalised guest experience.',
    overall_rating: 3.7,
    ratings: {
      work_life_balance: 3.5,
      culture: 3.9,
      management: 3.6,
      career_growth: 3.4,
      compensation: 3.5,
    },
    benefits: ['Staff meals', 'Hotel rate discounts for family', 'Annual performance bonus', 'Shift differential for night shifts', 'Training and development budget'],
    reviews: [
      {
        id: 'pepper-r1',
        role: 'Front Desk Receptionist',
        employment_status: 'Current',
        rating: 4,
        date: '2025-11',
        pros: 'Management genuinely listens to staff complaints and acts on them — rare in Cape Town hotels. Opera PMS training is provided. Good exposure to international guests during World Cup and summer events. Team culture is positive.',
        cons: 'Night audit shifts are very quiet but you\'re alone and it\'s a long night. Pay raises are tied to annual reviews that drag on for months. Parking costs are the employee\'s problem.',
        anonymous: true,
        helpful_count: 14,
        salary: 'R8 500/month',
      },
      {
        id: 'pepper-r2',
        role: 'Restaurant Waiter',
        employment_status: 'Former',
        rating: 3,
        date: '2025-06',
        pros: 'Consistent shifts with predictable hours, which is not common in restaurant work. Good baseline wage compared to standalone restaurants. The hotel restaurant is calmer than a high-volume standalone spot.',
        cons: 'Hotel restaurant tips are lower than a busy standalone restaurant. Some guests expect five-star service but it\'s a four-star operation — managing that expectation is tiring. Left for a role with better tips.',
        anonymous: true,
        helpful_count: 8,
        salary: 'R7 200/month + modest tips',
      },
      {
        id: 'pepper-r3',
        role: 'Housekeeping Attendant',
        employment_status: 'Current',
        rating: 4,
        date: '2025-09',
        pros: 'Stable employment, good team leader, supportive floor manager. The hotel provides all equipment and cleaning products — you\'re not cutting corners on supplies. Hotel benefits like discounted stays for family are a bonus.',
        cons: 'Room quota per shift is high. Green Point is not great for public transport if you finish late.',
        anonymous: false,
        author_name: 'Zodwa P.',
        helpful_count: 9,
        salary: 'R7 000/month',
      },
    ],
  },
  {
    id: 'the-chairman-restaurant',
    name: 'The Chairman Restaurant',
    industry: 'Restaurant',
    size: '11–50 employees',
    location: 'Durban, Morningside',
    description:
      'The Chairman Restaurant is a well-established fine dining restaurant in Morningside, Durban, known for its contemporary South African menu and curated wine list. A favourite for business lunches and special occasion dinners, The Chairman has built a loyal clientele over many years. The kitchen is demanding but produces high-quality food under experienced leadership.',
    overall_rating: 3.5,
    ratings: {
      work_life_balance: 3.0,
      culture: 3.7,
      management: 3.3,
      career_growth: 3.2,
      compensation: 3.5,
    },
    benefits: ['Staff meals', 'Tips pooled for FOH team', 'Annual Christmas bonus', 'Flexible leave in off-peak months'],
    reviews: [
      {
        id: 'chair-r1',
        role: 'Kitchen Porter',
        employment_status: 'Current',
        rating: 3,
        date: '2025-10',
        pros: 'Meals provided on shift are actually excellent — you eat what the kitchen produces. Team is decent, no bullying on the floor. Consistent hours, paid on time.',
        cons: 'Pay is basic and hasn\'t moved in 18 months. Kitchen gets extremely hot in summer. The work is physically hard — on your feet for 10 hours minimum.',
        anonymous: true,
        helpful_count: 7,
        salary: 'R4 800/month',
      },
      {
        id: 'chair-r2',
        role: 'Waiter',
        employment_status: 'Former',
        rating: 4,
        date: '2025-07',
        pros: 'The clientele is sophisticated and tips are very good, especially for lunch service. Good learning environment for fine dining service skills. Wine knowledge grows quickly because the list is serious.',
        cons: 'Management can be inconsistent — some weeks are organised, others chaotic. Uniform standards are strict which is fine in theory but the uniform is not provided.',
        anonymous: true,
        helpful_count: 12,
        salary: 'R6 800/month + tips',
      },
      {
        id: 'chair-r3',
        role: 'Commis Chef',
        employment_status: 'Former',
        rating: 3,
        date: '2025-04',
        pros: 'A solid fine dining kitchen to learn the basics properly. Head Chef has good technique and high standards.',
        cons: 'Long hours without appropriate overtime compensation. Split shifts are soul-destroying — you work lunch, go home for 2 hours, come back for dinner. No kitchen extraction during summer is brutal.',
        anonymous: true,
        helpful_count: 6,
        salary: 'R8 000/month',
      },
    ],
  },
  {
    id: 'salt-restaurant-group',
    name: 'Salt Restaurant Group',
    industry: 'Restaurant Group',
    size: '51–200 employees',
    location: 'Cape Town, Sea Point',
    description:
      'Salt Restaurant Group operates a portfolio of casual dining and upmarket restaurants across Cape Town\'s Atlantic Seaboard, with flagship locations in Sea Point and Clifton. Known for its Mediterranean-inspired menus and sea-facing locations, the group has grown significantly over the past five years and offers career progression within the group for motivated staff. It is one of the more professionally managed independent restaurant groups in the Western Cape.',
    overall_rating: 4.0,
    ratings: {
      work_life_balance: 3.6,
      culture: 4.2,
      management: 4.0,
      career_growth: 4.1,
      compensation: 3.8,
    },
    benefits: ['Dining discounts across all group restaurants', 'Internal promotion pathway', 'Staff meals', 'Annual incentive bonus for managers', 'Monthly team events'],
    reviews: [
      {
        id: 'salt-r1',
        role: 'Restaurant Manager',
        employment_status: 'Current',
        rating: 4,
        date: '2025-12',
        pros: 'One of the best-run restaurant groups in the Cape. Proper KPIs, structured performance reviews, real support from the group operations team. The brand is strong — guests trust Salt and that makes managing easier. Group dining discount is a genuine perk.',
        cons: 'High expectations come with the role — underperformance is dealt with swiftly. December in Sea Point is unrelenting. The salary for managers is competitive but should be higher given the responsibility.',
        anonymous: false,
        author_name: 'Ryan O.',
        helpful_count: 24,
        salary: 'R24 000/month',
      },
      {
        id: 'salt-r2',
        role: 'Senior Waiter',
        employment_status: 'Current',
        rating: 4,
        date: '2025-10',
        pros: 'Best tips I\'ve earned in my waitering career. Sea Point clientele are generous. Management doesn\'t micromanage the floor — they trust experienced staff. Colleagues are the best part of the job.',
        cons: 'Parking and transport to Sea Point from the southern suburbs is an issue without a car. Busy season rosters require negotiation well in advance. Some last-minute shift changes.',
        anonymous: true,
        helpful_count: 18,
        salary: 'R8 000/month + tips (R3 000–R6 000/month in season)',
      },
      {
        id: 'salt-r3',
        role: 'Hostess',
        employment_status: 'Former',
        rating: 4,
        date: '2025-06',
        pros: 'A very well-presented and professional environment. Guests are mostly lovely. The group invests in staff appearance and deportment training.',
        cons: 'Hostess pay is lower than FOH waiting staff and the work can be just as demanding during peak service. Growth out of the hostess role requires persistence.',
        anonymous: true,
        helpful_count: 9,
        salary: 'R7 000/month',
      },
    ],
  },
  {
    id: 'the-marine-hermanus',
    name: 'The Marine Hermanus',
    industry: 'Boutique Hotel / Guesthouse',
    size: '11–50 employees',
    location: 'Hermanus, Western Cape',
    description:
      'The Marine Hermanus is a historic boutique hotel perched above the Walker Bay coastline, one of the world\'s premier whale-watching destinations. Offering luxury accommodation, a fine dining restaurant, and a seafront pool, The Marine attracts an affluent domestic and international guest profile. Staff often live on the property during the season, creating a close-knit community environment unlike most urban hospitality roles.',
    overall_rating: 4.2,
    ratings: {
      work_life_balance: 4.0,
      culture: 4.5,
      management: 4.1,
      career_growth: 3.2,
      compensation: 3.6,
    },
    benefits: ['Live-in accommodation on property', 'All meals provided', 'Whale-watching access', 'End-of-season bonus', 'Uniform provided and laundered'],
    reviews: [
      {
        id: 'marine-r1',
        role: 'Housekeeping Attendant',
        employment_status: 'Current',
        rating: 5,
        date: '2025-11',
        pros: 'You live on the property in Hermanus with all meals included — the cost of living is essentially zero during season. The whale season from June to November means guests are genuinely excited to be there, which makes the atmosphere wonderful. Management is kind and organised.',
        cons: 'It is seasonal work — you need to plan for the off-season. Hermanus is small and isolated if you\'re used to city life. Internet connectivity at the staff quarters is patchy.',
        anonymous: true,
        helpful_count: 17,
        salary: 'R5 500/month + accommodation + meals',
      },
      {
        id: 'marine-r2',
        role: 'Breakfast Waiter',
        employment_status: 'Former',
        rating: 4,
        date: '2025-09',
        pros: 'Brilliant experience for someone wanting to try the seasonal hospitality lifestyle. Guests are gracious and well-travelled. The team that forms during the season becomes like a family. End-of-season bonus was a nice surprise.',
        cons: 'Breakfast starts at 6am which requires being up by 5:15. If you\'re not a morning person, this role will test you. Very limited nightlife in Hermanus if that\'s important to you.',
        anonymous: false,
        author_name: 'Anke S.',
        helpful_count: 20,
        salary: 'R5 200/month + accommodation + meals + tips',
      },
      {
        id: 'marine-r3',
        role: 'General Maintenance',
        employment_status: 'Former',
        rating: 4,
        date: '2025-05',
        pros: 'Live-in accommodation changes the economics completely. The property is beautiful — working maintenance here beats working in a block of flats. Management treats non-F&B staff with respect.',
        cons: 'Maintenance team is small so you carry a lot. On-call nights are part of the deal and not always compensated with time off.',
        anonymous: true,
        helpful_count: 5,
        salary: 'R6 000/month + accommodation + meals',
      },
    ],
  },
]
