import { Job } from './types'

// Fixed reference date for deterministic mock timestamps. MOCK_JOBS is imported
// directly by 'use client' components (e.g. CompanyClient), so calling the live
// clock at module load caused SSR/client hydration mismatches, the module
// evaluates at different wall-clock times on server vs browser. A constant is
// identical in both. `_now` replaces the old live-clock baseline; the relative
// offsets below are unchanged.
const _now = new Date('2026-06-23T09:00:00+02:00').getTime()

export const MOCK_JOBS: Job[] = [
  // ─── WAITERS / WAITRESSES ───────────────────────────────────────────────────
  {
    id: 'mock-1',
    title: 'Senior Waiter / Floor Captain',
    role_category: 'waiter',
    location: 'Cape Town, V&A Waterfront',
    employment_type: 'permanent',
    pay: 'R8 500/month + tips',
    description: `The One&Only Cape Town is looking for a polished, experienced Floor Captain to join our award-winning restaurant team at the Waterfront.\n\nAbout the role:\nYou will be responsible for leading a section of the floor, mentoring junior waiters, and delivering impeccable five-star service to an international guest base.\n\nRequirements:\n• Minimum 3 years fine-dining or 5-star hotel F&B experience\n• Confident wine knowledge and ability to recommend pairings\n• Impeccable grooming and communication skills\n• Fluency in English; a second language is an advantage\n• Ability to work evenings, weekends, and public holidays\n\nBenefits include:\n• Medical aid contribution after probation\n• Staff meals on shift\n• Group discount at One&Only properties worldwide\n• Structured career progression into supervisory roles`,
    employer_name: 'One&Only Cape Town',
    contact_method: '+27 21 431 5888',
    status: 'approved',
    created_at: new Date(_now - 0.5 * 86400000).toISOString(),
  },
  {
    id: 'mock-2',
    title: 'Waiter / Waitress',
    role_category: 'waiter',
    location: 'Johannesburg, Sandton',
    employment_type: 'permanent',
    pay: 'R7 000/month + tips',
    description: `Marble Restaurant, one of Joburg's most celebrated wood-fired dining destinations in the heart of Sandton, is hiring a waiter for our busy lunch and dinner service.\n\nWhat we're looking for:\n• At least 1 year of restaurant service experience\n• Warm, engaging personality with a genuine love for hospitality\n• Ability to carry multiple plates and work at pace\n• Knowledge of our South African-inspired menu and wine list\n• Flexible availability including weekends\n\nWhat we offer:\n• Competitive base + tips on a busy floor\n• Regular wine and menu training by our sommelier\n• Staff meals every shift\n• A high-energy, team-first culture\n\nMarble is part of the Chef David Higgs group. If you want to learn from some of the best in SA fine dining, this is your opportunity.`,
    employer_name: 'Marble Restaurant',
    contact_method: '+27 11 327 7579',
    status: 'approved',
    created_at: new Date(_now - 1 * 86400000).toISOString(),
  },
  {
    id: 'mock-3',
    title: 'Waitress / Waiter',
    role_category: 'waiter',
    location: 'Stellenbosch, Western Cape',
    employment_type: 'permanent',
    pay: 'R6 500/month + tips',
    description: `Spier Wine Farm, one of Stellenbosch's most visited wine estates, is seeking a waiter for our Eight restaurant and outdoor courtyard dining area.\n\nSpier is a working wine farm with five restaurants, a hotel, and an arts programme, offering a unique career in a beautiful setting.\n\nRole overview:\n• Table service for 60-80 covers per sitting\n• Wine service and food pairings using our estate wines\n• Interaction with local and international guests\n• Assist with outdoor functions and picnic setups during peak season\n\nRequirements:\n• Previous restaurant experience preferred but not essential, we train\n• Passion for wine and food\n• Comfortable on your feet all day\n• Reliable transport to Stellenbosch\n\nSeasonal staff may be considered for this role with a view to permanent placement.`,
    employer_name: 'Spier Wine Farm',
    contact_method: '+27 21 809 1100',
    status: 'approved',
    created_at: new Date(_now - 1 * 86400000).toISOString(),
  },
  {
    id: 'mock-4',
    title: 'Junior Waiter / Waitress',
    role_category: 'waiter',
    location: 'Durban, Umhlanga Ridge',
    employment_type: 'permanent',
    pay: 'R5 200/month + tips',
    description: `The Oyster Box, Umhlanga's most iconic five-star hotel, is looking for a junior waiter to join our busy Ocean Terrace team.\n\nThis is an excellent entry-level position for a candidate who wants to build a long-term career in luxury hospitality.\n\nTraining provided:\n• Full menu and allergen training\n• Wine and cocktail introduction\n• Five-star service standards and etiquette\n\nRequirements:\n• Matric / Grade 12\n• Well-spoken and presentable\n• Punctual and reliable\n• Willing to work shifts, weekends, and public holidays\n• KwaZulu-Natal residents preferred\n\nThe Oyster Box is part of the Red Carnation Hotel Collection and offers excellent staff benefits including a provident fund, medical aid, and internal transfer opportunities to the group's international properties.`,
    employer_name: 'The Oyster Box Hotel',
    contact_method: '+27 31 514 5000',
    status: 'approved',
    created_at: new Date(_now - 2 * 86400000).toISOString(),
  },
  {
    id: 'mock-5',
    title: 'Waiter / Waitress – Wine Estate',
    role_category: 'waiter',
    location: 'Franschhoek, Western Cape',
    employment_type: 'permanent',
    pay: 'R7 000/month + tips',
    description: `Faber Restaurant at Avondale Wine Farm is a celebrated fine-dining destination in the Franschhoek Valley. We're looking for a service-focused waiter who loves wine and wants to grow their knowledge in one of SA's most beautiful settings.\n\nFaber has been awarded the Eat Out Restaurant of the Year and our team is passionate about sharing that excellence with every guest.\n\nYou will:\n• Deliver table service for 40-cover sittings\n• Present and serve from a 200-label South African wine list\n• Host weekend wine-pairing lunches\n• Assist the sommelier with cellar and decanting duties\n\nRequirements:\n• Minimum 2 years restaurant experience\n• Wine Interest Certificate or WSET Level 1 advantageous\n• Own transport (Franschhoek location)\n• Full availability including Saturdays and Sundays`,
    employer_name: 'Faber at Avondale',
    contact_method: '+27 21 863 1160',
    status: 'approved',
    created_at: new Date(_now - 3 * 86400000).toISOString(),
  },
  {
    id: 'mock-6',
    title: 'Waiter / Waitress – Rooftop Bar',
    role_category: 'waiter',
    location: 'Cape Town, De Waterkant',
    employment_type: 'permanent',
    pay: 'R6 500/month + tips',
    description: `Gorgeous George boutique hotel in De Waterkant is hiring a waiter for our popular Rooftop Bar and Hugo's Restaurant on the first floor.\n\nOur venues attract a creative, international crowd and our team reflects that energy, stylish, attentive, and genuinely interested in people.\n\nThe role:\n• Cocktail and wine service on the rooftop\n• Food and beverage service in the restaurant\n• Evening and weekend shifts primarily\n• Participating in monthly training sessions with our mixologist\n\nIdeal candidate:\n• 1+ years in a bar or restaurant environment\n• Confident communicator\n• Comfortable with cash-up and point-of-sale systems\n• Cape Town ID or residence preferred\n\nTips on our rooftop are exceptional during summer season.`,
    employer_name: 'Gorgeous George Hotel',
    contact_method: '+27 21 433 2060',
    status: 'approved',
    created_at: new Date(_now - 3 * 86400000).toISOString(),
  },

  // ─── CHEFS ──────────────────────────────────────────────────────────────────
  {
    id: 'mock-7',
    title: 'Sous Chef',
    role_category: 'chef',
    location: 'Cape Town, Constantia',
    employment_type: 'permanent',
    pay: 'R22 000 – R26 000/month',
    description: `La Colombe, consistently ranked in SA's top 5 restaurants and regularly placed on the World's 50 Best list, is seeking a driven Sous Chef to support our Head Chef in this Relais & Châteaux property.\n\nThis is a rare opportunity to work at the absolute pinnacle of South African gastronomy.\n\nResponsibilities:\n• Oversee daily mise en place and kitchen operations\n• Manage and develop a team of 12 kitchen staff\n• Contribute to seasonal menu development\n• Maintain Relais & Châteaux quality standards\n• Manage food costs and wastage reduction\n\nRequirements:\n• Minimum 5 years professional kitchen experience\n• At least 2 years in a senior kitchen role\n• Formal culinary qualification (CCA, HTA, or equivalent)\n• Experience in modern European or contemporary cuisine\n• Passion for innovation and produce-led cooking\n\nSalary is negotiable for the right candidate.`,
    employer_name: 'La Colombe Restaurant',
    contact_method: '+27 21 794 2390',
    status: 'approved',
    created_at: new Date(_now - 0.5 * 86400000).toISOString(),
  },
  {
    id: 'mock-8',
    title: 'Chef de Partie – Pastry',
    role_category: 'chef',
    location: 'Cape Town, V&A Waterfront',
    employment_type: 'permanent',
    pay: 'R14 000 – R18 000/month',
    description: `The Westin Cape Town is looking for an experienced Pastry Chef de Partie to join our five-star kitchen team.\n\nThe Westin has over 500 rooms and our kitchen produces everything from breakfast buffet pastries to elaborate wedding cakes and individual fine-dining desserts.\n\nKey responsibilities:\n• Produce all pastry items for main restaurant and room service\n• Manage the pastry section during service\n• Create seasonal dessert specials in collaboration with the Head Pastry Chef\n• Train and supervise junior kitchen staff\n• Maintain HACCP food safety standards\n\nRequirements:\n• Professional culinary qualification with pastry focus\n• Minimum 3 years pastry experience in a 4- or 5-star establishment\n• Strong chocolate work and sugar showpiece experience advantageous\n• Ability to work early morning shifts and public holidays\n\nBenefits: medical aid, pension, staff cafeteria, Marriott group discounts.`,
    employer_name: 'The Westin Cape Town',
    contact_method: '+27 21 412 9999',
    status: 'approved',
    created_at: new Date(_now - 2 * 86400000).toISOString(),
  },
  {
    id: 'mock-9',
    title: 'Head Chef – Boutique Hotel',
    role_category: 'chef',
    location: 'Franschhoek, Western Cape',
    employment_type: 'permanent',
    pay: 'R35 000 – R42 000/month',
    description: `The Leeu Collection, a prestigious group of boutique hotels in Franschhoek and internationally, is looking for a Head Chef to lead the kitchen at their flagship Franschhoek property.\n\nYou'll have full creative control over a prix-fixe tasting menu that changes with the seasons and celebrates produce from the surrounding farms.\n\nThis is a career-defining role for an ambitious chef ready to plant their flag in South Africa's food capital.\n\nKey responsibilities:\n• Full ownership of the kitchen: menu, team, costs, and standards\n• Develop relationships with local farmers and artisan producers\n• Represent the restaurant at industry events and media\n• Maintain a brigade of 8 and oversee seasonal menu changes\n\nRequirements:\n• Minimum 3 years as Head Chef or strong Senior Sous Chef ready for the step up\n• Passion for wine-pairing and Cape Winelands cuisine\n• Proven ability to manage kitchen P&L\n• Portfolio of original menus required with application`,
    employer_name: 'Leeu Collection',
    contact_method: 'chefs@leeucollection.com',
    status: 'approved',
    created_at: new Date(_now - 4 * 86400000).toISOString(),
  },
  {
    id: 'mock-10',
    title: 'Commis Chef',
    role_category: 'chef',
    location: 'Johannesburg, Melrose',
    employment_type: 'permanent',
    pay: 'R7 500 – R9 000/month',
    description: `The Peech Hotel, a beloved boutique property in Melrose, is offering a commis chef position, an ideal first step for a recent culinary graduate.\n\nThe Peech is known for its organic garden-to-table philosophy and relaxed fine-dining approach. You'll work alongside experienced chefs who are passionate about mentoring new talent.\n\nYou will:\n• Assist in mise en place preparation across all sections\n• Learn station cooking under a Chef de Partie\n• Rotate through pastry, hot kitchen, and cold sections over 12 months\n• Participate in weekly skills training sessions\n\nRequirements:\n• Culinary qualification from an accredited institution (CCA, CAPSICUM, HTA, etc.)\n• Genuine passion for food and learning\n• Good knife skills and basic sauce knowledge\n• Willing to work early/late shifts and weekends\n\nRecent graduates are encouraged to apply, this is where careers begin.`,
    employer_name: 'The Peech Hotel',
    contact_method: '+27 11 537 9797',
    status: 'approved',
    created_at: new Date(_now - 5 * 86400000).toISOString(),
  },
  {
    id: 'mock-11',
    title: 'Sous Chef – Safari Lodge',
    role_category: 'chef',
    location: 'Sabi Sands, Mpumalanga',
    employment_type: 'permanent',
    pay: 'R20 000 – R24 000/month + live-in',
    description: `Singita Sabi Sand, one of Africa's most prestigious safari lodges, is recruiting a Sous Chef to join our remote kitchen team in the Sabi Sands Game Reserve.\n\nThis is a live-in, full-board position with 21 days on, 7 days off rotation.\n\nYou'll cook for up to 36 guests at a time, producing everything from breakfast and bush picnics to elaborate five-course dinners by candlelight in the bush.\n\nThe role:\n• Support the Head Chef across all meal services\n• Produce seasonal menus celebrating African ingredients\n• Manage kitchen in Head Chef's absence\n• Train and develop local kitchen staff\n\nBenefits:\n• Accommodation and all meals included\n• Return airfares to Johannesburg on rotation\n• Medical aid contribution\n• Staff wellness programme\n\nRequirements: 3+ years professional kitchen experience, lodge or remote kitchen experience advantageous, own vehicle for off-rotation travel.`,
    employer_name: 'Singita Sabi Sand',
    contact_method: 'talent@singita.com',
    status: 'approved',
    created_at: new Date(_now - 6 * 86400000).toISOString(),
  },

  // ─── BARTENDERS ─────────────────────────────────────────────────────────────
  {
    id: 'mock-12',
    title: 'Bartender – Craft Cocktail Bar',
    role_category: 'bartender',
    location: 'Cape Town, Bree Street',
    employment_type: 'permanent',
    pay: 'R9 000/month + tips',
    description: `Cause & Effect Cocktail Kitchen on Bree Street is Cape Town's most awarded cocktail destination. We're looking for a creative, technically skilled bartender to join our team.\n\nOur menu is built around locally sourced ingredients, house-made infusions, and cocktails designed to tell stories about South Africa. This is not a pour-and-serve job, it's a craft.\n\nWhat you'll be doing:\n• Behind-the-bar service and cocktail production during service\n• Assisting the head bartender with menu R&D and seasonal specials\n• Educating guests on our cocktail philosophy\n• Bar prep, infusion production, and stock management\n\nRequirements:\n• Minimum 2 years bartending experience in a cocktail bar\n• Strong knowledge of classic cocktails and spirits\n• RASA (Responsible Alcohol Service SA) certificate preferred\n• Available Tuesday–Sunday evenings\n\nOur team competes nationally and internationally, if you have ambition, this is the place.`,
    employer_name: 'Cause & Effect Cocktail Kitchen',
    contact_method: '+27 21 422 0377',
    status: 'approved',
    created_at: new Date(_now - 1 * 86400000).toISOString(),
  },
  {
    id: 'mock-13',
    title: 'Head Bartender',
    role_category: 'bartender',
    location: 'Johannesburg, Rosebank',
    employment_type: 'permanent',
    pay: 'R14 000 – R17 000/month',
    description: `The Radisson RED Johannesburg Rosebank is looking for a Head Bartender to lead our vibrant lobby bar and rooftop pool bar.\n\nRadisson RED is a lifestyle hotel brand, louder, bolder, more creative than a traditional hotel bar. We need a bartender who can match that energy.\n\nResponsibilities:\n• Lead a team of 3 bartenders\n• Develop seasonal cocktail menu in collaboration with F&B Manager\n• Manage bar stock, orders, and cost control\n• Ensure consistent, high-quality service standards\n• Host regular cocktail workshops for hotel guests\n\nRequirements:\n• Minimum 3 years bartending including 1 year in a supervisory role\n• Formal mixology training or international bartending certificate advantageous\n• Strong knowledge of South African craft spirits and wine\n• Excellent people management skills\n\nPackage includes medical aid, performance bonus, and free accommodation when working late shift.`,
    employer_name: 'Radisson RED Rosebank',
    contact_method: '+27 10 214 5800',
    status: 'approved',
    created_at: new Date(_now - 2 * 86400000).toISOString(),
  },
  {
    id: 'mock-14',
    title: 'Bartender',
    role_category: 'bartender',
    location: 'Durban, Point Waterfront',
    employment_type: 'permanent',
    pay: 'R7 500/month + tips',
    description: `The Gateway Yacht Club at Point Waterfront in Durban is hiring a bartender for our busy waterfront bar.\n\nWe serve everything from sundowner cocktails to post-race celebratory bottles. The crowd is mixed, locals, boaters, and tourists, and the vibe is always good.\n\nYour shifts:\n• Primarily afternoons and evenings, Wednesday to Sunday\n• Occasional Saturday morning yacht race service from 8am\n• New Year's Eve and December peak season is all hands on deck\n\nRequirements:\n• At least 1 year bar experience\n• Knowledge of cocktails, wine, and craft beer\n• Ability to work under pressure during busy weekend services\n• Responsible, reliable, and good with money (cash-up accountability)\n\nTips during summer season are very good. This is a great opportunity to work in one of Durban's most scenic locations.`,
    employer_name: 'Gateway Yacht Club',
    contact_method: '+27 31 307 6611',
    status: 'approved',
    created_at: new Date(_now - 3 * 86400000).toISOString(),
  },

  // ─── BARISTAS ───────────────────────────────────────────────────────────────
  {
    id: 'mock-15',
    title: 'Barista – Specialty Coffee',
    role_category: 'barista',
    location: 'Cape Town, City Bowl',
    employment_type: 'permanent',
    pay: 'R7 500 – R9 500/month',
    description: `Truth Coffee Roasting on Buitenkant Street, consistently ranked among the world's best coffee shops, is looking for a skilled barista to join our front bar team.\n\nTruth is a steampunk-inspired specialty coffee destination that takes coffee as seriously as any fine-dining kitchen. We roast our own single-origin coffees and train every barista from the ground up.\n\nThe role:\n• Espresso bar service during morning peak and throughout the day\n• Dialling in grinders and maintaining machine calibration\n• Pourovers, filter brewing, and cold brew service\n• Basic latte art required; advanced technique a strong advantage\n• Coffee consultations with wholesale clients\n\nRequirements:\n• Minimum 1 year specialty coffee experience\n• Barista Guild or SCASA training advantageous\n• Passion for origin, extraction, and flavour\n• Available early mornings from 7am\n\nTruth actively enters the SA Barista Championships, we support staff who want to compete.`,
    employer_name: 'Truth Coffee Roasting',
    contact_method: '+27 21 200 0440',
    status: 'approved',
    created_at: new Date(_now - 1 * 86400000).toISOString(),
  },
  {
    id: 'mock-16',
    title: 'Barista',
    role_category: 'barista',
    location: 'Johannesburg, Braamfontein',
    employment_type: 'permanent',
    pay: 'R6 000 – R7 500/month',
    description: `Rosetta Roastery, one of Johannesburg's most respected independent specialty coffee roasters, is hiring a barista for their Braamfontein cafe.\n\nRosetta sources directly from farms in East Africa, Colombia, and Brazil. You'll be making coffee you can be proud of.\n\nWe're looking for:\n• Someone who genuinely cares about the quality of what's in the cup\n• 6+ months specialty coffee bar experience\n• Confident espresso technique\n• Good palate and ability to distinguish flavour notes during cupping\n• Friendly, unhurried customer interaction style\n\nWhat we provide:\n• Full training on Rosetta's roast profiles and brewing parameters\n• Paid entry to SCASA regional competitions if you wish to compete\n• Monthly cupping sessions and origin education\n• 50% discount on all retail coffee\n\nShifts run Mon–Sat, 7am–4pm. We are closed Sundays.`,
    employer_name: 'Rosetta Roastery',
    contact_method: 'info@rosettas.co.za',
    status: 'approved',
    created_at: new Date(_now - 4 * 86400000).toISOString(),
  },
  {
    id: 'mock-17',
    title: 'Barista / All-Rounder',
    role_category: 'barista',
    location: 'Cape Town, Woodstock',
    employment_type: 'permanent',
    pay: 'R6 500/month',
    description: `Origin Coffee Roasting in Woodstock is Cape Town's original specialty roastery, we've been roasting since 2006. We're looking for a barista who can also assist with light food service and wholesale training.\n\nThis is a full-time position at our Old Biscuit Mill cafe.\n\nDay to day:\n• Espresso, filter, and batch brew service\n• Light breakfast and lunch food prep assistance\n• Stock management and opening/closing duties\n• Training new wholesale cafe clients on our equipment and technique\n\nWhat we're looking for:\n• 1+ years barista experience\n• Excellent time management and ability to multitask\n• Comfortable with basic food handling\n• Passion for coffee and genuine hospitality instinct\n\nWe're a team of 70+ across our roastery, cafe, and training centre, there's room to grow here.`,
    employer_name: 'Origin Coffee Roasting',
    contact_method: '+27 21 421 1000',
    status: 'approved',
    created_at: new Date(_now - 5 * 86400000).toISOString(),
  },

  // ─── HOUSEKEEPING ────────────────────────────────────────────────────────────
  {
    id: 'mock-18',
    title: 'Housekeeping Room Attendant',
    role_category: 'housekeeping',
    location: 'Cape Town, V&A Waterfront',
    employment_type: 'permanent',
    pay: 'R6 500/month',
    description: `The Cape Grace Hotel, a Leading Hotels of the World member at the V&A Waterfront, is looking for a Room Attendant to maintain our 120 suites and rooms to five-star standards.\n\nCape Grace is consistently rated one of Cape Town's top hotels and our housekeeping team is the backbone of that reputation.\n\nYour responsibilities:\n• Service of up to 14 rooms per shift\n• Turndown service for evening preparation\n• Replenishing minibar and amenities\n• Reporting maintenance issues\n• Handling guest requests promptly\n\nRequirements:\n• Previous hotel housekeeping experience preferred\n• Strong attention to detail\n• Physical fitness for a hands-on role\n• Excellent time management\n• Honest and trustworthy, you'll work in occupied rooms\n\nBenefits include medical aid, pension contribution, transport allowance, and staff meals. Standard shift: 7am–4pm with rotation.`,
    employer_name: 'Cape Grace Hotel',
    contact_method: '+27 21 410 7100',
    status: 'approved',
    created_at: new Date(_now - 2 * 86400000).toISOString(),
  },
  {
    id: 'mock-19',
    title: 'Housekeeping Supervisor',
    role_category: 'housekeeping',
    location: 'Sandton, Johannesburg',
    employment_type: 'permanent',
    pay: 'R11 000 – R13 500/month',
    description: `Sandton Sun, one of Sun International's flagship urban hotels, is recruiting a Housekeeping Supervisor to lead our rooms division team of 25.\n\nSandton Sun has 335 rooms and suites and hosts major corporate conferences throughout the year. Maintaining impeccable standards under this volume is a real operational challenge, and we need a supervisor who can meet it.\n\nKey responsibilities:\n• Daily supervision of room attendants and public area cleaners\n• Room inspections to Sun International quality standards\n• Linen inventory management and ordering\n• Staff scheduling and shift allocation\n• Liaison with front desk on check-in/check-out room readiness\n\nRequirements:\n• Minimum 2 years supervisory experience in hotel housekeeping\n• Knowledge of Opera PMS advantageous\n• Strong leadership and communication skills\n• Ability to work rotating shifts including weekends and public holidays`,
    employer_name: 'Sandton Sun',
    contact_method: '+27 11 780 5000',
    status: 'approved',
    created_at: new Date(_now - 3 * 86400000).toISOString(),
  },
  {
    id: 'mock-20',
    title: 'Laundry Attendant',
    role_category: 'housekeeping',
    location: 'Umhlanga, KwaZulu-Natal',
    employment_type: 'permanent',
    pay: 'R5 500/month',
    description: `The Oyster Box Hotel in Umhlanga is looking for a Laundry Attendant to join our busy linen services team.\n\nThe Oyster Box is a 5-star hotel with 86 rooms and multiple restaurants, our laundry operation runs 7 days a week and is essential to maintaining the hotel's legendary standards.\n\nResponsibilities:\n• Washing, drying, and pressing of guest and restaurant linen\n• Sorting and counting linen for room attendants\n• Operating industrial washing and pressing equipment\n• Maintaining laundry machine logs and reporting faults\n• Handling guest laundry with care and discretion\n\nRequirements:\n• Previous laundry or linen room experience advantageous\n• Physically fit for a standing role\n• Reliable and punctual\n• Comfortable with shift work including early mornings\n\nThe Oyster Box offers provident fund, medical aid contribution, and competitive conditions for entry-level hospitality staff.`,
    employer_name: 'The Oyster Box Hotel',
    contact_method: '+27 31 514 5000',
    status: 'approved',
    created_at: new Date(_now - 6 * 86400000).toISOString(),
  },

  // ─── FRONT DESK ──────────────────────────────────────────────────────────────
  {
    id: 'mock-21',
    title: 'Front Desk Receptionist',
    role_category: 'front_desk',
    location: 'Cape Town, Sea Point',
    employment_type: 'permanent',
    pay: 'R9 000 – R11 000/month',
    description: `POD Boutique Hotel on Sea Point's beachfront promenade is looking for a Front Desk Receptionist to be the first and last impression for our international and local guests.\n\nPOD is a design-led boutique hotel with 16 individually styled rooms and a loyal following of design-conscious travellers. Our front desk is more personal and relationship-driven than a big hotel.\n\nYour role:\n• Check-in and check-out using Opera PMS\n• Handle guest requests, concierge queries, and local recommendations\n• Night audit on a rotating basis\n• Assist with reservations and rate queries\n• Manage phone, email, and OTA message responses\n\nRequirements:\n• Diploma in Hospitality Management or equivalent experience\n• Minimum 1 year front desk experience\n• Opera or similar PMS experience preferred\n• Excellent written and spoken English\n• Available for evening and night audit shifts`,
    employer_name: 'POD Boutique Hotel',
    contact_method: '+27 21 430 5570',
    status: 'approved',
    created_at: new Date(_now - 1 * 86400000).toISOString(),
  },
  {
    id: 'mock-22',
    title: 'Guest Relations Officer',
    role_category: 'front_desk',
    location: 'Johannesburg, Sandton',
    employment_type: 'permanent',
    pay: 'R12 000 – R15 000/month',
    description: `The Saxon Hotel, Villas and Spa, arguably Johannesburg's finest five-star boutique hotel, is looking for a Guest Relations Officer to deliver personalised service to our distinguished local and international guests.\n\nThe Saxon hosted Nelson Mandela while he wrote Long Walk to Freedom. Our standards reflect that legacy.\n\nThe role demands:\n• Anticipation of VIP guest needs before they arise\n• Proactive communication with all departments on guest preferences\n• Handling complaints and service recovery with grace and urgency\n• Arranging bespoke experiences: restaurant bookings, game drives, helicopter tours\n• Contributing to our reputation management on review platforms\n\nRequirements:\n• Hospitality degree or equivalent\n• Minimum 2 years in a luxury hotel guest relations role\n• Polished presentation and exceptional interpersonal skills\n• Discretion, our guests expect absolute privacy\n• Afrikaans or French language skills advantageous`,
    employer_name: 'The Saxon Hotel',
    contact_method: 'hr@thesaxon.com',
    status: 'approved',
    created_at: new Date(_now - 2 * 86400000).toISOString(),
  },
  {
    id: 'mock-23',
    title: 'Night Auditor',
    role_category: 'front_desk',
    location: 'Pretoria, Hatfield',
    employment_type: 'permanent',
    pay: 'R9 500/month',
    description: `The Capital Moloko in Hatfield, Pretoria is looking for a Night Auditor to manage overnight front desk operations.\n\nThis is a primarily solo role running from 10pm to 7am. It suits a self-sufficient, detail-oriented candidate who enjoys a quieter pace and the responsibility of holding down the fort overnight.\n\nNightly responsibilities:\n• Complete Opera PMS night audit process\n• Late check-ins and early check-outs\n• Run and file daily revenue and occupancy reports\n• Monitor hotel security systems and liaise with security team\n• Handle overnight guest requests and minor issues\n\nRequirements:\n• Previous hotel front office experience required\n• Opera PMS knowledge essential\n• Reliable and able to work independently\n• Night shift: 5 nights per week including weekends\n\nThe Capital is SA's fastest-growing apartment hotel group, strong internal promotion track record.`,
    employer_name: 'The Capital Moloko',
    contact_method: '+27 12 003 5678',
    status: 'approved',
    created_at: new Date(_now - 5 * 86400000).toISOString(),
  },

  // ─── KITCHEN STAFF ───────────────────────────────────────────────────────────
  {
    id: 'mock-24',
    title: 'Kitchen Porter / Dishwasher',
    role_category: 'kitchen',
    location: 'Cape Town, Gardens',
    employment_type: 'permanent',
    pay: 'R5 000 – R5 800/month',
    description: `Societi Bistro in Gardens is looking for a reliable Kitchen Porter to support our busy kitchen team.\n\nSocieti has been a Cape Town favourite for 20+ years, we're a lively, family-friendly bistro that does high-volume lunch and dinner service.\n\nThis is a physically demanding role and the backbone of any kitchen:\n• Washing dishes, pots, and kitchen equipment\n• Keeping kitchen, pass, and back-of-house areas clean throughout service\n• Receiving and storing deliveries\n• Basic food prep assistance when required\n• End-of-service deep cleaning\n\nRequirements:\n• Reliable and hardworking\n• Able to handle standing for full shift (8–10 hours)\n• Willing to work evenings and weekends\n• Team player with a positive attitude\n\nNo experience required, we'll train you. Staff meals on every shift. Good people get promoted here, several of our Chef de Parties started as kitchen porters.`,
    employer_name: 'Societi Bistro',
    contact_method: '+27 21 424 2100',
    status: 'approved',
    created_at: new Date(_now - 3 * 86400000).toISOString(),
  },
  {
    id: 'mock-25',
    title: 'Food Prep / Kitchen Assistant',
    role_category: 'kitchen',
    location: 'Durban, Berea',
    employment_type: 'permanent',
    pay: 'R5 500/month',
    description: `Chairman's Restaurant in Berea, Durban is expanding our kitchen team and looking for a Food Prep Assistant to support morning mise en place.\n\nChairman's is a well-established restaurant known for our diverse menu of South African, Indian-influenced, and international dishes. We run a busy kitchen with two sittings nightly.\n\nYou will assist with:\n• Vegetable preparation, butchery prep, and sauce bases\n• Opening kitchen duties from 8am to 4pm shift\n• Restocking and maintaining prep station cleanliness\n• Supporting the Commis Chef during busy prep periods\n\nRequirements:\n• Basic kitchen skills and knife handling\n• Ability to follow recipes and portion control instructions\n• HACCP food safety awareness (training provided)\n• Reliable, punctual, and honest\n\nNo formal culinary qualification required. A willingness to learn and grow in a professional kitchen is what matters most.`,
    employer_name: "Chairman's Restaurant",
    contact_method: '+27 31 201 4444',
    status: 'approved',
    created_at: new Date(_now - 7 * 86400000).toISOString(),
  },

  // ─── HOSTS ───────────────────────────────────────────────────────────────────
  {
    id: 'mock-26',
    title: 'Restaurant Host / Hostess',
    role_category: 'host',
    location: 'Cape Town, Camps Bay',
    employment_type: 'permanent',
    pay: 'R7 000 – R8 500/month',
    description: `Azure Restaurant at The Twelve Apostles Hotel in Camps Bay is seeking a Front-of-House Host to manage guest arrivals and set the tone for our dining experience.\n\nThe Twelve Apostles is a Leading Hotels of the World property with stunning Twelve Apostles mountain views. Azure is one of Cape Town's most scenic and awarded restaurants.\n\nThe role:\n• Welcome and seat arriving guests with warmth and precision\n• Manage the reservation system (Dineplan or ResDiary)\n• Coordinate with floor manager on table flow and waiting times\n• Handle phone and OTA reservation enquiries\n• Upsell experiences: private dining, sundowner packages, birthday set-ups\n\nRequirements:\n• Excellent presentation, this is a very visible front-of-house role\n• Previous hosting or front-of-house experience in a premium restaurant\n• Warm, confident personality\n• Afternoon and evening availability (primarily 3pm–11pm shifts)`,
    employer_name: 'The Twelve Apostles Hotel',
    contact_method: '+27 21 437 9000',
    status: 'approved',
    created_at: new Date(_now - 1 * 86400000).toISOString(),
  },
  {
    id: 'mock-27',
    title: 'Events Host',
    role_category: 'host',
    location: 'Johannesburg, Midrand',
    employment_type: 'event',
    pay: 'R600 – R800 per event',
    description: `Premier Event Catering, one of Gauteng's most established corporate and private event caterers, is looking for freelance Events Hosts for an ongoing roster of corporate year-ends, award ceremonies, and private functions.\n\nWe have events every weekend from October to December and need a pool of reliable, presentable, experienced hosts.\n\nShifts are typically:\n• Corporate cocktail parties (5pm–11pm)\n• Award dinners (6pm–midnight)\n• Wedding receptions (12pm–10pm)\n• Private birthday functions\n\nRequirements:\n• Previous event hosting or front-of-house experience\n• Immaculate presentation, uniform provided\n• Excellent English communication skills\n• Available on short notice for Gauteng-based events\n• Own reliable transport\n\nThis is a flexible role to fit around other commitments. Rates increase for seniors who take on floor captain duties.`,
    employer_name: 'Premier Event Catering',
    contact_method: '+27 11 805 3000',
    status: 'approved',
    created_at: new Date(_now - 2 * 86400000).toISOString(),
  },

  // ─── MANAGERS ────────────────────────────────────────────────────────────────
  {
    id: 'mock-28',
    title: 'Restaurant Manager',
    role_category: 'manager',
    location: 'Cape Town, Woodstock',
    employment_type: 'permanent',
    pay: 'R22 000 – R28 000/month',
    description: `The Pot Luck Club, Luke Dale-Roberts's iconic tapas restaurant at the Silo District, is looking for an experienced Restaurant Manager to lead our floor operations.\n\nThe Pot Luck Club is one of South Africa's most celebrated restaurants and the floor reflects that, high-energy, creative, and demanding.\n\nResponsibilities:\n• Full operational management of floor service (70 covers)\n• Manage and develop a team of 18 floor staff\n• Work closely with Luke and the kitchen on new menu rollouts\n• Drive revenue through upselling, private dining bookings, and cocktail pairings\n• Maintain Eat Out standard-aligned service protocols\n• P&L management, staffing budgets, and rostering\n\nRequirements:\n• Minimum 3 years restaurant management experience\n• Strong fine-dining service knowledge\n• Excellent wine and spirits knowledge\n• Proven team leadership in a high-pressure environment\n• Available evenings and weekends`,
    employer_name: 'The Pot Luck Club',
    contact_method: 'hr@thetestkitchengroup.com',
    status: 'approved',
    created_at: new Date(_now - 1 * 86400000).toISOString(),
  },
  {
    id: 'mock-29',
    title: 'Food & Beverage Manager',
    role_category: 'manager',
    location: 'Johannesburg, Sandton',
    employment_type: 'permanent',
    pay: 'R30 000 – R38 000/month',
    description: `Fairlawns Boutique Hotel & Spa, an exclusive 5-star property in Morningside, Sandton is looking for an F&B Manager to oversee all dining operations.\n\nFairlawns has three dining venues, a 1920s cocktail bar, afternoon teas, private dining rooms, and a full banqueting function, this is a comprehensive F&B leadership role.\n\nThe role covers:\n• Day-to-day management of restaurant, bar, and room service\n• Menu development in partnership with the Head Chef\n• Revenue management across all F&B venues\n• Banqueting and private event execution\n• Staff recruitment, training, and performance management\n• F&B cost control and monthly P&L reporting\n\nRequirements:\n• Hospitality Management degree or equivalent experience\n• Minimum 5 years F&B experience including 2+ years at management level\n• Strong financial acumen\n• Wine qualification (Wine Interest Certificate or above) preferred\n• Passionate about creating exceptional guest experiences`,
    employer_name: 'Fairlawns Boutique Hotel',
    contact_method: 'hr@fairlawns.co.za',
    status: 'approved',
    created_at: new Date(_now - 4 * 86400000).toISOString(),
  },
  {
    id: 'mock-30',
    title: 'Assistant Café Manager',
    role_category: 'manager',
    location: 'Cape Town, Kloof Street',
    employment_type: 'permanent',
    pay: 'R14 000 – R17 000/month',
    description: `Jason Bakery, one of Cape Town's most beloved artisan bakeries and cafés, is looking for an Assistant Manager to support daily operations across our Kloof Street and city bowl locations.\n\nJason has built a cult following for our croissants, sourdough, and brunch, the queue out the door every Saturday morning is proof. We need a manager who can maintain that standard under pressure.\n\nYour responsibilities:\n• Opening and closing procedures\n• Staff scheduling and daily briefing\n• Cash management and daily banking\n• Stock control and supplier liaison\n• Customer service and complaint resolution\n• Support the Head Baker with morning production oversight\n\nRequirements:\n• 2+ years in a café or casual restaurant management role\n• Specialty coffee knowledge (you'll be behind the bar occasionally)\n• Strong organisational skills\n• Must be available early mornings from 6am\n• Food safety supervisor certificate advantageous`,
    employer_name: 'Jason Bakery',
    contact_method: '+27 21 424 5644',
    status: 'approved',
    created_at: new Date(_now - 5 * 86400000).toISOString(),
  },

  // ─── SEASONAL ────────────────────────────────────────────────────────────────
  {
    id: 'mock-31',
    title: 'Seasonal Waiter / Waitress – Summer',
    role_category: 'waiter',
    location: 'Cape Town, Clifton',
    employment_type: 'seasonal',
    pay: 'R6 000/month + tips',
    description: `SOULed OUT Clifton, a high-energy beach-adjacent restaurant and bar, is looking for seasonal waiters for the October–March Cape Town summer season.\n\nThis is one of the best-tipped floors in Cape Town during summer. International tourists, big groups, celebrations, the energy is electric and the earning potential is real.\n\nSeasonal role: October 2025 – March 2026\n\nShifts:\n• Lunch and dinner service, 7 days per week during peak weeks\n• Reduced schedule in shoulder weeks\n• Guaranteed minimum hours each week\n\nRequirements:\n• Previous restaurant experience\n• Ability to carry and multitask\n• Upbeat, confident personality\n• Flexible availability for peak season including all public holidays\n\nPrevious seasonal staff have been offered permanent positions at the end of summer. This is a great foot in the door.`,
    employer_name: 'SOULed OUT Clifton',
    contact_method: '+27 21 438 2021',
    status: 'approved',
    created_at: new Date(_now - 1 * 86400000).toISOString(),
  },
  {
    id: 'mock-32',
    title: 'Seasonal Bartender – Wine Estate Events',
    role_category: 'bartender',
    location: 'Stellenbosch, Western Cape',
    employment_type: 'seasonal',
    pay: 'R7 500/month',
    description: `Waterkloof Wine Estate in Somerset West is hiring a seasonal bartender for our busy summer wedding and events season (November–April).\n\nWaterkloof hosts approximately 3 weddings per weekend during peak season. Our biodynamic wine estate is a sought-after venue and we need a bartender who can represent the brand with pride.\n\nYou'll be:\n• Bar service at weddings, wine tastings, and corporate events\n• Working our estate wine bar and restaurant on non-event days\n• Assisting with wine service and wine-pairing discussions\n• Bar setup and breakdown for outdoor events\n\nRequirements:\n• Previous bar experience\n• Basic wine knowledge (training provided on Waterkloof wines)\n• Own transport to Somerset West\n• Available for weekend events, this role is primarily weekends\n• Smart, presentable, reliable\n\nLive-in option available on the estate during the contract period.`,
    employer_name: 'Waterkloof Wine Estate',
    contact_method: '+27 21 858 1292',
    status: 'approved',
    created_at: new Date(_now - 3 * 86400000).toISOString(),
  },
  {
    id: 'mock-33',
    title: 'Casual Event Waiter / Waitress',
    role_category: 'waiter',
    location: 'Johannesburg, Various',
    employment_type: 'event',
    pay: 'R650 – R900 per event',
    description: `Nozala Events Staffing, Gauteng's most active hospitality staffing agency, is looking to grow our database of casual event waiters for 2025–2026.\n\nWe place staff at:\n• Corporate year-end functions\n• Gala dinners and award ceremonies\n• Weddings and private celebrations\n• Music festivals and sports hospitality\n• Pop-up restaurant experiences\n\nYou choose your availability. We send you relevant opportunities. You confirm. Simple.\n\nRate structure:\n• Standard events: R650–750/day\n• Premium (5-star, formal service): R800–900\n• Senior and supervisory roles: R1,000–1,200\n\nRequirements:\n• At least 6 months restaurant or events service experience\n• Smart, clean, presentable\n• Excellent English communication\n• Reliable transport anywhere in Gauteng\n• Willing to commit to confirmed bookings (cancellation policy applies)\n\nApply now with your name, experience summary, and availability. We'll get you placed quickly.`,
    employer_name: 'Nozala Events Staffing',
    contact_method: '+27 72 034 5678',
    status: 'approved',
    created_at: new Date(_now - 2 * 86400000).toISOString(),
  },
  {
    id: 'mock-34',
    title: 'Breakfast Chef',
    role_category: 'chef',
    location: 'Pretoria, Menlyn',
    employment_type: 'permanent',
    pay: 'R10 500 – R13 000/month',
    description: `Protea Hotel by Marriott Menlyn in Pretoria is looking for a Breakfast Chef to manage our morning kitchen service, producing breakfast for up to 150 covers daily.\n\nThis is a morning role: 5am–2pm, Monday to Sunday on a 5-day rotation. If you're a morning person who likes to finish early, this is ideal.\n\nResponsibilities:\n• A la carte and buffet breakfast production\n• Egg station, live cooking, and action stations\n• Supervising two kitchen assistants\n• Stock management and daily order for breakfast supplies\n• Maintaining HACCP standards throughout service\n\nRequirements:\n• Culinary qualification\n• 2+ years breakfast or all-day dining kitchen experience\n• Consistent early morning availability\n• Attention to detail and ability to move fast during peak service\n\nMarriott benefits include international discount programme, pension fund, and annual performance bonus.`,
    employer_name: 'Protea Hotel Menlyn',
    contact_method: '+27 12 348 8900',
    status: 'approved',
    created_at: new Date(_now - 6 * 86400000).toISOString(),
  },
  {
    id: 'mock-35',
    title: 'Concierge / Bellman',
    role_category: 'front_desk',
    location: 'Cape Town, City Bowl',
    employment_type: 'permanent',
    pay: 'R8 500/month + tips',
    description: `Belmond Mount Nelson Hotel, Cape Town's iconic pink palace and one of Africa's legendary grand hotels, is looking for a Concierge/Bellman to join our guest experience team.\n\nBelmond guests are global travellers who expect nothing short of perfection. Our concierge team is their guide to Cape Town, from Table Mountain hikes to the best local fish braai and everything between.\n\nResponsibilities:\n• Guest arrivals, luggage handling, and hotel orientation\n• Personalised recommendations: restaurants, experiences, itineraries\n• Booking tickets, transfers, and tours\n• Delivering items to rooms and responding to guest requests\n• Maintaining the front entrance and lobby presentation\n\nRequirements:\n• Previous luxury hotel or concierge experience\n• Outstanding knowledge of Cape Town and surrounds\n• Warm, proactive personality\n• Professional grooming and conduct\n• Clean driver's licence (occasional guest transfers)\n\nTips from appreciative Belmond guests are substantial.`,
    employer_name: 'Belmond Mount Nelson Hotel',
    contact_method: '+27 21 483 1000',
    status: 'approved',
    created_at: new Date(_now - 4 * 86400000).toISOString(),
  },
]
